# Generated by Django 3.0.1 on 2019-12-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product_aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='remote_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
