# Generated by Django 3.0.1 on 2019-12-27 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('product_aggregator', '0002_offer_remote_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'created'},
        ),
    ]
